---
title: "Continuous and GLM-Type Outcomes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{use-linear-glm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
rm(list=ls())
library(RoboCar)
```

## Adjustment with Continuous Outcomes

The dataset that we will use for this is included in the package.

```{r}
data <- RoboCar::data_sim
data$A <- as.factor(data$A)
```

### ANOVA Model

```{r}
fit.anova <- robincar_linear(df = data, 
                             response_col="y",
                             treat_col="A",
                             covariate_cols=c("x1", "x3"),
                             car_scheme="simple",
                             adj_method="ANOVA",
                             vcovHC="HC0")
```

### ANCOVA model with biased coin randomization

```{r}
fit.ancova <- robincar_linear(df = data, 
                              response_col="y",
                              treat_col="A",
                              strata_cols=c("z1", "z2"),
                              covariate_cols=c("x1", "x3"),
                              car_scheme="biased-coin",
                              adj_method="ANCOVA",
                              vcovHC="HC0")
fit.ancova$result
```


### ANHECOVA model with Pocock-Simon randomization and linear contrast

```{r}
fit.anhecova <- robincar_linear(df = data, 
                                response_col="y",
                                treat_col="A",
                                strata_cols=c("z1", "z2"),
                                covariate_cols=c("x1", "x3"),
                                car_scheme="biased-coin",
                                adj_method="ANCOVA",
                                vcovHC="HC0",
                                contrast_h="diff")

fit.anhecova$contrast$result
```

## Adjustment with Continuous Outcomes

